_target_: lloca.framesnet.equi_frames.LearnedRestFrames
is_global: false
random: false
compile: false
ortho_kwargs:
 method: gramschmidt
 eps_norm: 1e-10
 eps_reg_coplanar: 1e-4
 eps_reg_lightlike: 1e-10

defaults:
 - equivectors: equimlp