_target_: lloca.frames.equi_frames.LearnedOrthogonalFrames
is_global: false
random: false
fix_params: false
ortho_kwargs:
 method: gramschmidt
 eps_norm: 1e-15
 eps_reg_coplanar: 1e-10
 eps_reg_lightlike: 1e-10

defaults:
 - equivectors: equigraph
