_target_: experiments.amplitudes.wrappers.PELICANWrapper
particle_type: null
network_float64: null

net:
 _target_: pelican.nets.PELICAN

 in_channels_rank0: 0
 in_channels_rank1: null
 in_channels_rank2: 1
 out_rank: 0
 out_channels: 1

 num_blocks: 4
 hidden_channels: 32
 increase_hidden_channels: 1.

 map_multipliers: true
 factorize: true
 activation: gelu
 aggr: mean
 compile: true

defaults:
 - framesnet: identity
