_target_: experiments.amplitudes.wrappers.TransformerWrapper
particle_type: null
use_float64: null

net:
 _target_: tensorframes.nn.transformer.TFTransformer

 in_channels: null
 attn_reps: "8x0n+2x1n"
 out_channels: 1

 num_blocks: 8
 num_heads: 8

defaults:
 - lframesnet: identity
