_target_: experiments.amplitudes.wrappers.TransformerWrapper
particle_type: null
network_float64: null

net:
 _target_: lloca.nn.transformer.Transformer

 in_channels: null
 attn_reps: "8x0n+2x1n"
 out_channels: 1

 num_blocks: 8
 num_heads: 8

defaults:
 - framesnet: identity
