_target_: experiments.amplitudes.wrappers.TransformerWrapper
particle_type: null

net:
 _target_: tensorframes.nn.transformer.TFTransformer

 in_reps: null
 attn_reps: "8x0n+2x1n"
 out_reps: "1x0n"

 num_blocks: 8
 num_heads: 8

defaults:
 - lframesnet: identity
