_target_: experiments.amplitudes.wrappers.MLPWrapper
particle_type: null
use_float64: null

net:
 _target_: tensorframes.nn.mlp.MLP

 in_shape: null
 out_shape: 1
 hidden_channels: 128
 hidden_layers: 5

defaults:
 - lframesnet: identity
