_target_: experiments.tagging.wrappers.BaselineParTWrapper
use_pair_attn: true

net:
 _target_: experiments.baselines.particletransformer.ParticleTransformer
 _partial_: true
 num_classes: null
 input_dim: 7

 pair_input_dim: null
 use_amp: true
 trim: true

defaults:
 - lframesnet: identity
