_target_: experiments.toptagging.wrappers.BaselineParTWrapper
mean_aggregation: true
in_reps: null

net:
 _target_: experiments.baselines.particletransformerv2.ParticleTransformerTagger
 _partial_: true
 num_classes: 1

defaults:
 - lframesnet: identity
