_target_: experiments.tagging.wrappers.BaselineGraphNetWrapper
mean_aggregation: true
in_reps: null

net:
 _target_: experiments.baselines.graphnet.GraphNet
 _partial_: true

 in_channels: null
 out_channels: 1
 hidden_channels: 128

 num_blocks: 2
 num_layers_mlp1: 2
 num_layers_mlp2: 0

defaults:
 - lframesnet: identity
