_target_: experiments.tagging.wrappers.BaselineParTWrapper
in_reps: null

net:
 _target_: experiments.baselines.particletransformerv2.ParticleTransformerTagger
 _partial_: true
 num_classes: null

defaults:
 - lframesnet: identity
