_target_: experiments.eventgen.wrappers.TransformerCFM

net:
 _target_: lloca.nn.transformer.Transformer

 in_channels: null
 out_channels: null
 attn_reps: "5x0n+2x1n"

 num_blocks: 6
 num_heads: 8

defaults:
 - lframesnet: identity