_target_: experiments.tagging.wrappers.GraphNetWrapper
in_reps: null
out_reps: null
remove_local_tagging_features: false

net:
 _target_: tensorframes.nn.graphnet.TFGraphNet
 _partial_: true

 in_reps: null
 hidden_reps: "64x0n+16x1n" # reps can be varied, but number of channels should stay fixed
 out_reps: null

 num_blocks: 3
 num_layers_mlp1: 3
 num_layers_mlp2: 0

defaults:
 - lframesnet: identity