_target_: experiments.toptagging.wrappers.GraphNetWrapper
mean_aggregation: true
in_reps: null

net:
 _target_: tensorframes.nnhep.graphnet.TFGraphNet
 _partial_: true

 in_channels: null
 out_channels: 1
 hidden_reps: "8x0n+4x1n"

 num_blocks: 2
 num_layers_mlp1: 2
 num_layers_mlp2: 0

lframesnet:
 _target_: tensorframes.lframes.nonequi_lframes.IdentityLFrames
