_target_: experiments.tagging.wrappers.GraphNetWrapper

net:
 _target_: tensorframes.nn.graphnet.TFGraphNet
 _partial_: true

 in_reps: null
 hidden_reps: "96x0n+24x1n"
 out_reps: null

 num_blocks: 3
 num_layers_mlp1: 1
 num_layers_mlp2: 0

defaults:
 - lframesnet: identity