_target_: experiments.tagging.wrappers.GraphNetWrapper

net:
 _target_: tensorframes.nn.graphnet.TFGraphNet
 _partial_: true

 in_reps: null
 hidden_reps: "32x0n+16x1n+4x2n"
 out_reps: null

 num_blocks: 2
 num_layers_mlp1: 2
 num_layers_mlp2: 0

defaults:
 - lframesnet: identity