_target_: experiments.toptagging.wrappers.ProtoNetWrapper
mean_aggregation: true
post_layer: null

net:
 _partial_: true
 _target_: experiments.toptagging.protonet.ProtoNet
 in_reps: 1x0n+1x1n
 hidden_reps: ["8x0n+8x1n", "32x0n+32x1n", "64x0n+64x1n"] 
 out_reps: 1x0n

 checkpoint_blocks: false
 second_hidden_reps: null

  #angularmodule:
  #  _target_: tensorframes.nn.embedding.axial.AxisWiseBesselEmbedding
  #  num_frequencies: 10

  #radialmodule:
  #    _target_: tensorframes.nn.embedding.radial.BesselEmbedding
  #    num_frequencies: 10s

lframesnet:
 _partial_: true
 _target_: experiments.toptagging.lframesnet.LFramesNet
 approach: identity
 layers: 2
 hidden_channels: 32
 #radial module

angular_module:
 _target_: tensorframes.nn.embedding.axial.TrivialAxisWiseEmbedding

radial_module:
 _target_: tensorframes.nn.embedding.radial.TrivialRadialEmbedding
