_target_: experiments.toptagging.wrappers.ProtoNetWrapper
mean_aggregation: true
post_layer: null

net:
 _partial_: true
 _target_: experiments.toptagging.protonet.ProtoNet
 in_reps: 8x0n+1x1n
 hidden_reps: ["8x0n+8x1n", "16x0n+16x1n"] 
 hidden_layer_number: [2, 1] 
 out_reps: 1x0n

 checkpoint_blocks: false
 second_hidden_reps: null

 aggr: add
 concatenate_receiver_features_in_mlp1: True
 concatenate_receiver_features_in_mlp2: True
 use_edge_feature_product: False

lframesnet:
 _partial_: true
 _target_: experiments.toptagging.lframesnet.LFramesNet
 approach: identity
 layers: 2
 hidden_channels: 32

angular_module:
 _target_: tensorframes.nn.embedding.axial.TrivialAxisWiseEmbedding

radial_module:
 _target_: tensorframes.nn.embedding.radial.TrivialRadialEmbedding