_target_: experiments.tagging.wrappers.BaselineParTWrapper
in_channels: null
out_channels: null

net:
 _target_: experiments.baselines.particletransformer.ParticleTransformer
 _partial_: true
 input_dim: null
 num_classes: null

 use_amp: true

 use_pre_activation_pair: false
 pair_input_dim: 4
 cls_block_params:
  dropout: 0
  attn_dropout: 0
  activation_dropout: 0

defaults:
 - lframesnet: identity
