_target_: experiments.tagging.wrappers.ParticleNetWrapper
in_channels: null
out_channels: null
global_points: False

net:
 _target_: tensorframes.nn.particlenet.TFParticleNet
 _partial_: true
 num_classes: null
 conv_params: [[16, [64, 64, 64]], [16, [128, 128, 128]], [16, [256, 256, 256]]]
 fc_params: [[128, 0.1]]
 input_dims: null
 hidden_reps_list: ["7x0n", "32x0n+8x1n", "64x0n+16x1n"]

defaults:
 - lframesnet: identity
