_target_: experiments.tagging.wrappers.BaselineParticleNetWrapper
in_channels: null
out_channels: null

net:
 _target_: experiments.baselines.particlenet.ParticleNet
 _partial_: true
 num_classes: null

defaults:
 - lframesnet: identity
