_target_: experiments.tagging.wrappers.LGATrWrapper

net:
 _target_: lgatr.LGATr

 in_mv_channels: 1
 in_s_channels: null
 out_mv_channels: 1
 out_s_channels: null
 hidden_mv_channels: 16
 hidden_s_channels: 32

 num_blocks: 12
 attention:
  num_heads: 8
 mlp:
  activation: gelu

defaults:
 - lframesnet: identity
