_target_: experiments.tagging.wrappers.MIParTWrapper
in_channels: null
out_channels: null
use_amp: false
add_fourmomenta_backbone: false

net:
 _target_: experiments.baselines.mipart.MIParticleTransformer
 _partial_: true
 input_dim: null
 num_classes: null

defaults:
 - framesnet: identity
