_target_: experiments.tagging.wrappers.TransformerWrapper
add_tagging_features_lframesnet: true
symmetry_breaking: []

net:
 _target_: tensorframes.nn.transformer.TFTransformer
 _partial_: true

 in_reps: null
 attn_reps: "8x0n+2x1n" # reps can be varied, but number of channels should stay fixed
 out_reps: null

 num_blocks: 8
 num_heads: 8

defaults:
 - lframesnet: identity