_target_: tensorframes.equivectors.equigraph.EquiGraphNet
_partial_: true

n_vectors: null
num_scalars: null
hidden_channels: 128
hidden_vectors: 1
num_layers_mlp: 2
num_blocks: 1
dropout_prob: null

include_edges: true
operation: add
nonlinearity: exp
aggr: sum
layer_norm: true
fm_norm: true
