_target_: lloca.lframes.equi_lframes.LearnedPolarDecompositionLFrames
is_global: false
random: false
fix_params: false
gamma_max: null
gamma_hardness: 1
deterministic_boost: null
ortho_kwargs:
 method: gramschmidt
 eps_norm: 1e-15
 eps_reg: 1e-10

defaults:
 - equivectors: equigraph