_target_: tensorframes.lframes.equi_lframes.LearnedPolarDecompositionLFrames
is_global: false
random: false
ortho_kwargs:
 method: gramschmidt
 eps_norm: 1e-10
 eps_reg: 1e-4

defaults:
 - equivectors: equigraph