_target_: tensorframes.lframes.equi_lframes.LearnedPolarDecompositionLFrames
is_global: false
random: false
fix_params: false
ortho_kwargs:
 method: gramschmidt
 eps_norm: 1e-15
 eps_reg: 1e-10

defaults:
 - equivectors: equigraph