_target_: lloca.equivectors.lgatr.LGATrVectors
_partial_: true

n_vectors: null
num_scalars: null

net:
 _target_: lgatr.nets.LGATr
 _partial_: true

 in_mv_channels: 1
 in_s_channels: null
 out_mv_channels: ${model.lframesnet.equivectors.net.hidden_mv_channels}
 out_s_channels: 0
 hidden_mv_channels: 2
 hidden_s_channels: 4

 num_blocks: 1
 attention:
  num_heads: 1
 mlp:
  activation: gelu
