iterations: 250000
batchsize: 256

optimizer: Adam
betas: [.9, .999]
eps: 1e-8
weight_decay: 0

lr: 1e-4
scheduler: null
scheduler_scale: 1
cosanneal_eta_min: 0
reduceplateau_factor: 0.1
reduceplateau_patience: 50
onecycle_max_lr: 10
onecycle_pct_start: 0.3

es_patience: 100
es_load_best_model: true

log_every_n_steps: 1000
validate_every_n_steps: 1252

clip_grad_norm: 1000
clip_grad_value: null
max_grad_norm: null
