iterations: 100000
batchsize: 512

optimizer: AdamW
lr: 1e-3
betas: [.99, .999]
eps: 1e-8
weight_decay: 0

scheduler: CosineAnnealingLR
scheduler_scale: 1
cosanneal_eta_min: 0
reduceplateau_factor: 0.1
reduceplateau_patience: 50
onecycle_max_lr: 10

es_patience: 100
es_load_best_model: true

log_every_n_steps: 200
validate_every_n_steps: 5000

clip_grad_norm: 1000
clip_grad_value: null