iterations: 50000
batchsize: 512

# optimizer: default AdamW
optimizer: AdamW
betas: [.99, .999]
eps: 1e-8
weight_decay: 0

# LR: Default CosineAnnealingLR
lr: 1e-3
scheduler: CosineAnnealingLR
scheduler_scale: 1
cosanneal_eta_min: 0
reduceplateau_factor: 0.1
reduceplateau_patience: 50
onecycle_max_lr: 10
onecycle_pct_start: 0.3

es_patience: 100
es_load_best_model: true

log_every_n_steps: 200
validate_every_n_steps: 5000

clip_grad_norm: null
clip_grad_value: null
max_grad_norm: null
