# hyperparameters from https://arxiv.org/abs/2202.03772 section 5.1 and 5.2
batchsize: 512
lr: 1e-3
weight_decay: 0.01
iterations: 46875 # 20 epochs
validate_every_n_steps: 2343 # after each epoch
optimizer: Ranger

# rest differently for convenience
scheduler: CosineAnnealingLR

defaults:
 - default
