# hyperparameters from https://arxiv.org/abs/1902.08570 section III.B
batchsize: 1024
optimizer: AdamW
weight_decay: 0.0001
iterations: 23437 # 20 epochs
validate_every_n_steps: 1171 # after each epoch

# rest differently for convenience
lr: 1e-3
scheduler: CosineAnnealingLR

defaults:
 - default
