# hyperparameters from https://arxiv.org/abs/1902.08570 section III.B
batchsize: 384
optimizer: AdamW
weight_decay: 0.0001
iterations: 62500 # 20 epochs
validate_every_n_steps: 3125 # after each epoch
scheduler: particlenet-scheduler
lr: 3e-4

defaults:
 - tag_default
