_target_: tensorframes.lframes.equi_lframes.LearnedOrthogonalLFrames
ortho_kwargs:
 method: gramschmidt
 eps_norm: 1e-10
 eps_reg_coplanar: 1e-8
 eps_reg_lightlike: 1e-4

defaults:
 - equivectors: equigraph
