_target_: tensorframes.lframes.equi_lframes.OrthogonalLearnedLFrames
in_nodes: null
hidden_channels: 32
num_layers: 2
ortho_kwargs:
 method: gramschmidt
 eps_norm: 1e-10
 eps_reg_coplanar: 1e-4
 eps_reg_lightlike: 1e-4
 use_float64: true