_target_: tensorframes.lframes.equi_lframes.LearnedOrthogonalLFrames
is_global: false
random: false
ortho_kwargs:
 method: gramschmidt
 eps_norm: 1e-15
 eps_reg_coplanar: 1e-10
 eps_reg_lightlike: 1e-10

defaults:
 - equivectors: equigraph
