_target_: tensorframes.lframes.equi_lframes.RestLFrames
_partial_: true
in_nodes: null
hidden_channels: 32
num_layers: 2
spurion_lframes_replacements: null
ortho_kwargs:
 method: gramschmidt
 eps_norm: 1e-10
 eps_reg: 1e-4
 use_float64: true