_target_: experiments.amplitudes.wrappers.MLPWrapper
particle_type: null
network_float64: null

net:
 _target_: lloca.backbone.mlp.MLP

 in_shape: null
 out_shape: 1
 hidden_channels: 128
 hidden_layers: 3

defaults:
 - framesnet: identity
