_target_: experiments.amplitudes.wrappers.GATrWrapper
particle_type: null
use_float64: null

net:
 _target_: experiments.baselines.gatr.nets.GATr

 in_mv_channels: 1
 in_s_channels: null
 out_mv_channels: 1
 out_s_channels: null
 hidden_mv_channels: 8
 hidden_s_channels: 8

 num_blocks: 2
 attention:
  num_heads: 2

defaults:
 - lframesnet: identity
 - /base_attention@net.attention
 - /base_mlp@net.mlp