_target_: experiments.amplitudes.wrappers.TransformerWrapper
particle_type: null
use_float64: null

net:
 _target_: lloca.nn.transformer.TFTransformer

 in_channels: null
 attn_reps: "8x0n+2x1n"
 out_channels: 1

 num_blocks: 2
 num_heads: 2

defaults:
 - lframesnet: identity
