_target_: experiments.tagging.wrappers.BaselineTransformerWrapper
in_channels: null

net:
 _target_: experiments.baselines.transformer.Transformer
 _partial_: true

 in_channels: null
 num_classes: null
 hidden_channels: 64

 num_blocks: 2
 num_heads: 4

defaults:
 - lframesnet: identity
