_target_: experiments.tagging.wrappers.BaselineParticleNetWrapper

net:
 _target_: experiments.baselines.particlenet.ParticleNet
 _partial_: true
 num_classes: null
 input_dims: 7

defaults:
 - lframesnet: identity
