_target_: experiments.tagging.wrappers.BaselineGraphNetWrapper
in_reps: null

net:
 _target_: experiments.baselines.graphnet.GraphNet
 _partial_: true

 in_channels: null
 num_classes: null
 hidden_channels: 64

 num_blocks: 2
 num_layers_mlp1: 2
 num_layers_mlp2: 0

defaults:
 - lframesnet: identity
