_target_: experiments.tagging.wrappers.BaselineParTWrapper
in_reps: null
use_pair_attn: true

net:
 _target_: experiments.baselines.particletransformer.ParticleTransformer
 _partial_: true
 num_classes: null
 input_dim: 7

defaults:
 - lframesnet: identity
