_target_: experiments.eventgen.wrappers.TransformerCFM
beam_reference: lightlike
two_beams: true
add_time_reference: true
scalar_dims: [0, 3]

net:
 _target_: tensorframes.nn.transformer.TFTransformer

 in_channels: null
 out_channels: null
 attn_reps: "8x0n+2x1n"

 num_blocks: 1
 num_heads: 4

defaults:
 - lframesnet: identity