_target_: experiments.tagging.wrappers.GraphNetWrapper
in_channels: null
out_channels: null

net:
 _target_: tensorframes.nn.graphnet.TFGraphNet
 _partial_: true

 in_channels: null
 hidden_reps: "16x0n+4x1n"
 out_channels: null

 num_blocks: 2
 num_layers_mlp1: 2
 num_layers_mlp2: 0

defaults:
 - lframesnet: identity
