_target_: experiments.tagging.wrappers.GraphNetWrapper
in_reps: null
out_reps: null

net:
 _target_: tensorframes.nn.graphnet.TFGraphNet
 _partial_: true

 in_reps: null
 hidden_reps: "16x0n+4x1n"
 out_reps: null

 num_blocks: 2
 num_layers_mlp1: 2
 num_layers_mlp2: 0

defaults:
 - lframesnet: identity
