_target_: experiments.tagging.wrappers.TransformerWrapper
in_channels: null
out_channels: null
use_float64: null

net:
 _target_: tensorframes.nn.transformer.TFTransformer
 _partial_: true

 in_channels: null
 attn_reps: "8x0n+2x1n"
 out_channels: null

 num_blocks: 2
 num_heads: 2
 
defaults:
 - lframesnet: identity
