_target_: experiments.tagging.wrappers.BaselineParTWrapper
in_channels: null
out_channels: null

net:
 _target_: experiments.baselines.particletransformer.ParticleTransformer
 _partial_: true
 input_dim: null
 num_classes: null

 pair_input_dim: null
 use_amp: false
 trim: true

defaults:
 - lframesnet: identity
