_target_: experiments.tagging.wrappers.LGATrWrapper

net:
 _target_: lgatr.LGATr

 in_mv_channels: 1
 in_s_channels: null
 out_mv_channels: 1
 out_s_channels: null
 hidden_mv_channels: 4
 hidden_s_channels: 16

 num_blocks: 1
 attention:
  num_heads: 2
 mlp:
  activation: gelu

defaults:
 - lframesnet: identity
