_target_: experiments.tagging.wrappers.TransformerWrapper
symmetry_breaking: []

net:
 _target_: tensorframes.nn.transformer.TFTransformer
 _partial_: true

 in_reps: null
 attn_reps: "8x0n+2x1n"
 out_reps: null

 num_blocks: 2
 num_heads: 2
 
defaults:
 - lframesnet: identity
