exp_type: amplitudes
exp_name: amp

data:
 dataset : zgg
 data_path : data/
 subsample: null
 permutation_symmetry: true
 preprocess_momentum: false
 train_test_val: [.4, .5, .1]

evaluation:
 eval_set: [train, test, val]
 batchsize: 4096

plotting:
 histograms: true
 delta: false
 delta_prepd: false

defaults:
 - default
 - training: amp_new_default
 - model: amp_transformer
