exp_type: amplitudes
exp_name: amp

data:
 dataset : zgg 
 data_path : /gpfs/projects/acad/hepml/datasets/lorentz-frames/
 subsample: null
 permutation_symmetry: true
 standardize: true
 prepare: com_genlorentz
 train_test_val: [.4, .5, .1]
 mass_reg: 1e-5

evaluation:
 eval_set: [train, test, val]
 batchsize: 4096
 save_lframes: false

plotting:
 histograms: false
 delta: false
 delta_prepd: false

defaults:
 - default
 - training: amp_default
 - model: amp_transformer
