exp_type: jctagging
exp_name: jc_debug

data:
 data_dir: /remote/gpu02/breso/lorentz-gatr-old/data/JetClass/Pythia
 features: default
 data_config: null
 train_files_range: [0, 100]
 test_files_range: [100,120]
 val_files_range: [120,125]

jc_params:
 num_workers: 4
 fetch_step: 0.01
 extra_selection: null
 extra-test-selection: null
 fetch_by_files: false
 in_memory: False
 not_remake_weights: False
 steps_per_epoch: null
 steps_per_epoch_val: null
 events_per_file: 100000
 async_load: false
 split_num: 1

evaluation:
 batchsize: 1024
 eval_set: [test]

plotting:
 roc: false
 score: false

defaults:
 - tagging
