exp_type: luigitagging
exp_name: luigi_debug

data:
 data_dir: data/topxl/
 features: default
 add_scalar_features: true
 train_files_range: [0, 1]
 test_files_range: [0, 1]
 val_files_range: [0, 1]

jc_params:
 num_workers: 4
 fetch_step: 0.01
 extra_selection: null
 extra-test-selection: null
 fetch_by_files: False
 in_memory: False
 not_remake_weights: False
 steps_per_epoch: null
 steps_per_epoch_val: null

evaluation:
 batchsize: 1024
 eval_set: [test]

plotting:
 roc: false
 score: false

defaults:
 - tagging
