exp_name: sweep-amp

trials: 1  # one trial run per job
seed: null
n_startup_trials: 100
optuna_db: 'runs/${exp_name}/optuna/optuna.db'

model_name: amp_transformer

cfg_overrides:
 - evaluation.eval_set=[val,test]
