data:
 rescale_data: true
 beam_reference: timelike
 two_beams: true
 add_time_reference: true
 add_scalar_features: true
 add_tagging_features: true
 mass_reg: 1e-2

evaluation:
 batchsize: 512
 save_roc: false
 eval_set: [train, test, val]

plotting:
 roc: true
 loss: true
 score: true

defaults:
 - default
 - training: default
 - model: graphnet
 - hydra
 - _self_
