data:
 add_tagging_features_lframesnet: false
 rescale_data: true
 beam_reference: lightlike
 two_beams: true
 add_time_reference: true
 mass_reg: 1e-2
 eps_tagging: 1e-10

evaluation:
 batchsize: 512
 save_roc: false
 eval_set: [train, test, val]

plotting:
 roc: true
 loss: true
 score: true

defaults:
 - default
 - training: default
 - model: graphnet
