data:
 add_tagging_features_lframesnet: false
 beam_reference: lightlike
 two_beams: true
 add_time_reference: true
 mass_reg: 5e-3
 spurion_scale: 1

evaluation:
 batchsize: 512
 save_roc: false
 eval_set: [train, test, val]

plotting:
 roc: true
 loss: true
 score: true

defaults:
 - default
 - training: default
 - model: tag_graphnet
