exp_type: topxltagging
exp_name: topxl_debug

data:
 data_dir: /gpfs/scratch/acad/hepml/TopXL/
 features: default
 data_config: null
 add_scalar_features: True
 train_files_range: [0, 499]
 test_files_range: [500, 599]
 val_files_range: [600, 624]

topxl_params:
 num_workers: 2
 fetch_step: 0.01
 extra_selection: null
 extra-test-selection: null
 fetch_by_files: False
 in_memory: False
 not_remake_weights: False
 steps_per_epoch: null
 steps_per_epoch_val: null
 events_per_file: 100000
 async_load: True

evaluation:
 batchsize: 1024
 eval_set: [test]

plotting:
 roc: true
 score: true

defaults:
 - tagging
