exp_type: ttbar
exp_name: ttbar_debug

data:
 n_jets: 0
 data_path: /remote/gpu06/spinner/lorentz-gatr/data
 data_path_0j: ${data.data_path}/ttbar_0j.npy
 data_path_1j: ${data.data_path}/ttbar_1j.npy
 data_path_2j: ${data.data_path}/ttbar_2j.npy
 data_path_3j: ${data.data_path}/ttbar_3j.npy
 data_path_4j: ${data.data_path}/ttbar_4j.npy
 subsample: null
 train_test_val: [.5, .4, .1]
 base_type: 4
 use_delta_r_min: true
 use_pt_min: true
 spurions:
  beam_reference: timelike
  two_beams: true
  add_time_reference: true
  scalar_dims: [0, 3]

odeint:
 method: rk4
 rtol: 1e-5
 atol: 1e-5
 options:
  step_size: 0.01

cfm:
 embed_t_dim: 8
 embed_t_scale: 30.
 hutchinson: true
 coordinates: StandardLogPtPhiEtaLogM2
 geometry:
  type: simple
  periodic: true
 transforms_float64: true

evaluation:
 sample: true
 save_samples: false
 nsamples: 1000000
 batchsize: 4096
 eval_log_prob: [val]
 classifier: true

plot: true
plotting:
 loss: true
 fourmomenta: true
 jetmomenta: true
 preprocessed: true
 virtual: true
 delta: true
 deta_dphi: true
 log_prob: true
 reweighted: false
 create_mask: false

defaults:
- training: eg_default
- model: eg_transformer
- classifier: classifier
- default
