_target_: lloca.framesnet.equi_frames.LearnedPDFrames
is_global: false
random: false
fix_params: false
gamma_max: null
gamma_hardness: 10
deterministic_boost: null
compile: false
ortho_kwargs:
 method: gramschmidt
 eps_norm: 1e-15
 eps_reg_coplanar: 1e-16
 eps_reg_lightlike: 1e-20

defaults:
 - equivectors: equimlp