_target_: lloca.framesnet.equi_frames.LearnedSO2Frames
is_global: false
random: false
fix_params: false
eps_reg_lightlike: 1e-10
ortho_kwargs:
 method: gramschmidt
 eps_norm: 1e-10
 eps_reg: 1e-4

defaults:
 - equivectors: equimlp
