_target_: lloca.framesnet.equi_frames.LearnedSO13Frames
is_global: false
random: false
fix_params: false
compile: false
ortho_kwargs:
 method: gramschmidt
 eps_norm: 1e-15
 eps_reg_coplanar: 1e-20
 eps_reg_lightlike: 1e-20

defaults:
 - equivectors: equimlp
