_target_: lloca.frames.equi_frames.LearnedOrthogonal3DFrames
is_global: false
random: false
fix_params: false
ortho_kwargs:
 method: gramschmidt
 eps_norm: 1e-10
 eps_reg: 1e-4

defaults:
 - equivectors: equigraph
